### ISSUE TITLE
When using other than resnet18 as a proxy model, the accuracy seems wrong, especially in terms of white box

### ISSUE THREAD

**Issue by Studying-bo** [Trustworthy-AI-Group/TransferAttack#45]
Excuse me, I have recently been borrowing your framework to test my method. I have noticed that in terms of improving transferability based on input diversity, your evaluation data for various methods below are all based on resnet18 as a proxy model. When I When using resnet101 as a proxy model to evaluate the following method, for the white box model, its effect is very low, only about 80%. I have not found the cause of the problem. I hope you can answer it.

**Comment by Zhijin-Ge** [comment]
Hi, we have also noticed this issue! The reason for this problem is due to different versions of the model weights, the weights currently used are the latest version of the weights which are more robust, you can find this information at [here](https://pytorch.org/vision/stable/models.html). 

You can load the old version of the weights so that it is possible to achieve a 100% attack success rate under the white box setting.
`model = models.__dict__[model_name](weights="IMAGENET1K_V1") # Old weights, can achieve 100% attack success rates`
`model = models.__dict__[model_name](weights="DEFAULT") # New weights`

**Comment by Studying-bo** [comment]
Thank you very much for your patient answer. I successfully solved my problem through the way you provided. Thank you again for your contribution to the fight against the attack direction

**Comment by Studying-bo** [comment]
Thank you very much for your patient answer. I successfully solved my problem through the way you provided. Thank you again for your contribution to the Adversarial Attack direction

**Comment by Truman168** [comment]
> Hi, we have also noticed this issue! The reason for this problem is due to different versions of the model weights, the weights currently used are the latest version of the weights which are more robust, you can find this information at [here](https://pytorch.org/vision/stable/models.html).
> 
> You can load the old version of the weights so that it is possible to achieve a 100% attack success rate under the white box setting. `model = models.__dict__[model_name](weights="IMAGENET1K_V1") # Old weights, can achieve 100% attack success rates` `model = models.__dict__[model_name](weights="DEFAULT") # New weights`

你好，我想问一下，这种权重初始化对应的torchvision版本是多少呀，我用这种初始化方法会报没有weights这个错

**Comment by xiaosen-wang** [comment]
Please refer to [requirements.txt](https://github.com/Trustworthy-AI-Group/TransferAttack/blob/main/requirements.txt) in this repo. Thanks.

**Comment by Truman168** [comment]
> Please refer to [requirements.txt](https://github.com/Trustworthy-AI-Group/TransferAttack/blob/main/requirements.txt) in this repo. Thanks.
Thanks!
